InternalDeveloperPlatform/public-site

content/community/experts/_index.md
=> add myself as an expert

content/ecosystem/build-vs-buy/frameworks/backstage.md, content/ecosystem/build-vs-buy/frameworks/gimlet.md
=> Infrastructure Orchestration - duplicate fix

content/ecosystem/build-vs-buy/frameworks/_index.md, content/ecosystem/build-vs-buy/frameworks/devopsbox.md, content/ecosystem/build-vs-buy/frameworks/humanitec.md
We are happy to join this community. I hope we can help to promote knowledge about good DevOps concepts.
As a first commit, I'm sending our platform description.
=> DevOpsBox - solution description

content/ecosystem/build-vs-buy/build-it-yourself/_index.md, content/ecosystem/build-vs-buy/build-it-yourself/ambassador-labs.md
Hi, I've added the Ambassador Labs info to the DIY section and tested the Hugo build. Please reach out if you have any questions.
=> Added Ambassador Labs info to DIY section

content/learn/core-components/application-configuration-management.md, content/learn/core-components/environment-management.md, content/learn/core-components/infrastructure-orchestration.md, content/learn/how-do-internal-developer-platforms-relate-to-other-concepts.md, content/learn/what-is-an-internal-developer-platform.md
I would actually do this for ALL pictures in the site.
=> Made some small pictures clickable

content/learn/what-is-an-internal-developer-platform.md
8b0404b is fixing a typo.
99bc8df is fixing the pronouns towards gender neutrality.
=> Fix typo and gender neutrality

content/community/articles.md
Adding Achievers abattoir blog to the articles page
=> Adding Achievers abattoir solution blog to the articles page

content/ecosystem/build-vs-buy/frameworks/gimlet.md
Hello,
I'm the maker of Gimlet. Updated some copy and attributes to match the https://gimlet.io site.
=> Updated Gimlet info

content/ecosystem/integrations/databases/_index.md, content/ecosystem/integrations/databases/azure-sql.md
Added Azure SQL to Databases for integration.
=> Added Azure-SQL to Databases.

content/community/articles.md, content/ecosystem/build-vs-buy/frameworks/_index.md, content/ecosystem/build-vs-buy/frameworks/mia-platform.md
Added Mia-Platform as one of "Buy" options
=> Mia-Platform Framework

content/ecosystem/build-vs-buy/build-it-yourself/_index.md
There are two portrainer mention on, i just remove one of them
=> remove double portrainer CE

content/ecosystem/paas-devops-platforms/dyrectorio.md
Add dyrector.io Platform to the PaaS DevOps Platform section. Please @christophcrichter and @FL303 review it and If you can suggest something else I can incorporate it.
=> chore: add dyrectorio to ecosystem

content/ecosystem/platform-tooling/developer-portals/_index.md, content/ecosystem/platform-tooling/developer-portals/backstage.md, content/ecosystem/platform-tooling/developer-portals/cortex.md, content/ecosystem/platform-tooling/developer-portals/opslevel.md, content/ecosystem/platform-tooling/developer-portals/port.md, content/ecosystem/platform-tooling/infrastructure-as-code/pulumi.md, content/ecosystem/platform-tooling/infrastructure-control-planes/upbound.md, content/ecosystem/platform-tooling/kubernetes-control-planes/gimlet.md, content/ecosystem/platform-tooling/kubernetes-control-planes/shipa.md
Fixed aliases and added Opslevel and Cortex to the developer portals category.
=> Fixed aliases and added new tools

content/ecosystem/paas-devops-platforms/_index.md, content/ecosystem/paas-devops-platforms/coherence.md
We believe that Coherence (withcoherence.com) belongs in this page. Please let us know if there's a better place or if you think it does not fit. We're also happy to tweak the content we've added if needed. Thanks!
=> Add coherence to IDP list

content/ecosystem/platform-tooling/developer-portals/atlassian-compass.md
Adding Compass to developer portal listings. :)
=> Compass from Atlassian

content/learn/why-use-an-internal-developer-platform.md
There were two TLDRs. One has been removed.
=> Removed extra TLDR

content/ecosystem/platform-tooling/developer-portals/_index.md, content/ecosystem/platform-tooling/developer-portals/configure8.md
Adds configure8 as an Internal Developer Portal option.
=> Adds configure8 as an Internal Developer Portal option

content/community/consultancies/polarsquad.md
Polar Squad previously was "Polarsquad". Fixed the company name and added short introduction.
=> Fix the Polar Squad company name and add description

content/community/articles.md
=> Add Internal Developer Platform on AWS to Articles

content/community/consultancies/platform-engineers-io.md
=> Used link instead of button for article and case study

content/ecosystem/platform-tooling/developer-portals/port.md
=> changed port page

content/ecosystem/platform-tooling/developer-portals/autocloud.md
=> chore: create autocloud.md

content/community/consultancies/_index.md, content/community/consultancies/consol.md
Kindly add ConSol to the list of consultancies.  I am a member of their platform engineering team.
=> Add ConSol to consultancies

content/ecosystem/platform-tooling/developer-portals/configure8.md
=> [bug] - configure8 title and url missmatch

content/ecosystem/platform-tooling/platform-orchestrators/_index.md, content/ecosystem/platform-tooling/platform-orchestrators/massdriver.md
Adding massdriver to platform tooling
=> Adding massdriver

content/community/consultancies/infracloud-technologies.md
@christophcrichter did some minor fixes. mind checking and merging please.
=> minor fixes to InfraCloud listing (under Consultancies)

content/community/articles.md
Here are our recently published articles under Platform Engineering - sharing with the community.
=> Adding platform engineering articles by InfraCloud

content/ecosystem/platform-tooling/monitoring/_index.md, content/ecosystem/platform-tooling/monitoring/elastic.md
Add Elastic to the list of monitoring vendors.
=> Add Elastic to monitoring solutions

content/community/articles.md
I have included the link to my blog post titled 'Creating Infrastructure Using Backstage Templates, Terraform, and GitHub Actions' on the article page.
=> added backstage blog

content/ecosystem/platform-tooling/security/selefra.md
=> Fixed selefra link

content/community/consultancies/_index.md, content/community/consultancies/virtuslab.md
Hi,
I'd like to add [VirtusLab](https://virtuslab.com/) to the ecosystem of companies specialising in platform engineering.
=> Add VirtusLab consultancy

content/community/consultancies/_index.md, content/community/consultancies/croz.md
Hi!
I want to introduce CROZ company as a consultancy.
=> Introduce CROZ as a consultancy

content/community/articles.md
Hey. This is my first time contributing to this site. I hope our article on engineering standards fits with the content of the site.
=> Add engineering standards article

content/_index.md
* Updated book theme (due to deprecation warnings)
* Updated front page (since Kelsey's Twitter feed is no longer available)
=> Updated book theme and front page

Dockerfile
Updated base image incl. Hugo version
=> Update to new Hugo version

content/ecosystem/platform-tooling/developer-portals/_index.md, content/ecosystem/platform-tooling/developer-portals/arctir-flightdeck.md
Adds Flightdeck content as well as modifies portal index.
=> Add Arctir Flightdeck to Developer Portals

content/ecosystem/platform-tooling/developer-portals/tempest.md
Changes in this Pull Request:
* Added a missing word on the Tempest Developer Portal page for improved clarity.
* Removed unnecessary white spaces on the Tempest Developer Portal page to enhance formatting.
=> Typo in Tempest developer portal page

content/ecosystem/platform-tooling/developer-portals/relyio.md
This pull request includes updates to the `content/ecosystem/platform-tooling/developer-portals/relyio.md` file, focusing on improving the accuracy and clarity of the information about Rely.io. The most important changes include updating URLs, modifying descriptions, and adding links to core features.
Updates to URLs and descriptions:
* Updated the website URL from `rely.io` to `www.rely.io` to ensure consistency and accuracy.
* Changed the "Live Demo" link to a "Request Free Trial" link to reflect the current offering.
* Clarified the self-hosted options description to provide more details about the integration engine and self-service agent.
* Updated the source description to indicate that some components are open source, rather than all.
* Expanded the use case description to include …
=> Update details for Developer portals/Rely.io
